spring:
  datasource:
    url: jdbc:mysql://47.98.217.61:3306/schoolWall?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: wuchenyu
