page:
  size: 8

spring:
  datasource:
#    url: jdbc:mysql://47.98.217.61:3306/schoolWall?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: wuchenyu
    url: jdbc:mysql://127.0.0.1:3306/sw_2021_1_3?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
